### PR TITLE
Bump minimum rust version to 1.43

### PR DESCRIPTION
**Pull request by kchibisov**

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Want to add the changelog in this one?

**Comment by kchibisov** [comment]
I'm not sure that it matters?

**Comment by kchibisov** [comment]
Note, there's no such thing as a minimum rust version on a cargo toml level. it matters for alacritty, but I'm not sure that it matters for us.

**Comment by chrisduerr** [comment]
> Note, there's no such thing as a minimum rust version on a cargo toml level. it matters for alacritty, but I'm not sure that it matters for us.

It does. Because clients like Alacritty will fail building if the minimum version is bumped without clear communication.

**Comment by kchibisov** [comment]
>It does. Because clients like Alacritty will fail building if the minimum version is bumped without clear communication.

In which section that change should go?

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
